### ISSUE TITLE
This is all really confusing

### ISSUE THREAD

**Issue by madsimmons07** [ufotechnologies/amp-android#1]
All I want to do is get some specific music tracks playing for my Slack Team as background ambience when they are on either the Slack mobile app or web app.  Can Amp do that for my team?  The Slack App Directory { www.slack.com/apps/A33N6EPC6-amp } offers me a vague description that Amp plays music using requests and that Spotify, an Android device, or Chromecast are involved somehow.  Before troubleshooting anything, I want to make sure that this app can even do what I need it to do, first off.

Second, and for the record, I'm decently versed in how Slack functions, but I'm brand new to Spotify.  I have downloaded Amp - Music Bot, Spotify, and Slack for my Android phone and in Windows I downloaded Spotify and I'm using the web apps for the other two in Google Chrome, but now what do I do?  I found and saved a few tracks on Spotify that I wanted to test playing on Slack, but I'm completely lost with how Amp links the two together.  The amp bot on Slack is inactive and I have no idea how to turn it on from either the computer or my phone.  The mobile app for Amp only asks me for an encryption key that I don't have or know what it's use is, so I can't use it for anything yet.  There is no FAQ page that I can find on the website { https://ufo.ai/amp/ } or even a simple step by step set of instructions for setting this up.  Spotify doesn't seem to have any new buttons or menus added where I can integrate Amp or Slack together either.  What am I missing here and where can I get this encryption key?

**Comment by pschroen** [comment]
Hi Michael,

This app is still very new and you're the first to submit an issue, this is good feedback though as I need to make it more consumer friendly and will add setup steps to the site.

Also note there is a future update I'd like to do that plays radio or playlists from Spotify, but right now it more works like a jukebox. I should update the Slack description...

1) From your Android device use the "Add to Slack" button and then on the Encrypted token page press "Open in Amp".

2) Log in to Spotify and you should see an indicator at the top of the app that says you're connected to Slack as "amp".

3) In Slack you should see your "amp" bot is online and you make requests by either sending it a DM or add the bot to a #music channel.

Let me know if that helps, thanks!

**Comment by madsimmons07** [comment]
I appreciate the quick reply.  It's good to see developers trying to provide what people want with their Slack experience!  I'll reply again after I've given it a try.

**Comment by pschroen** [comment]
In the meantime I've updated the short description, and added the three steps above to the site.

Hope that helps and let me know if you have any luck, cheers!
